services:
  - type: web
    name: loja-brinquedos-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: loja-brinquedos-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h

databases:
  - name: loja-brinquedos-db
    databaseName: loja_brinquedos
    user: loja_brinquedos_user
    plan: free 